from random import seed, randint
from input_handler import input_handler

(in_seed, nb_of_elements) = input_handler()
####
seed(in_seed)
L_rand = [randint(0, 99) for _ in range(nb_of_elements)]
print("\nThe list is:", L_rand)
####
max_elem = 0
min_elem = 99
for elem in L_rand:
    if elem > max_elem:
        max_elem = elem
    elif elem < min_elem:
        min_elem = elem
print("The maximum element in the list is: ", max_elem)
print("The maximum element generated by the python function is: ", max(L_rand))
print("The minimum element in the list is: ", min_elem)
print("The minimum element generated by the python function is: ", min(L_rand))
